package com.example.midtermspringboot.STATUS;

public enum Status {
    SUCCESSFULLY_REGISTERED,
    SUCCESSFULLY_LOGIN,
    SUCCESSFULLY_LOGOUT,
    SUCCESSFULLY_DELETED,
    USER_ALREADY_EXISTS,
    SUCCESSFULLY_UPDATED,
    FAILURE
}
