package com.example.midtermspringboot.status;

public enum Status {
    A_NEW_CLIENT_REGISTERED_SUCCESSFULLY,
    THE_CLIENT_LOGIN_SUCCESSFULLY,
    THE_CLIENT_LOGOUT_SUCCESSFULLY,
    DELETED,
    THE_CLIENT_ALREADY_EXISTS,
    UPDATED,
    FAILED
}
